baseURL = 'https://xacalite.github.io/TechBlog'
languageCode = 'en-us'
title = 'Klue Tech Blog'
theme = "ananke"


[params]
   favicon = "images/klue-favicon.png"   
   site_logo = "images/klue-logo-small.png"
