baseURL = 'http://klue-tech-blog.com/'
languageCode = 'en-us'
title = 'Klue Tech Blog'
theme = "ananke"


[params]
   author = "Kaywin"
   favicon = "images/klue-favicon.png"   
   site_logo = "images/klue-logo-small.png"
